-- Migrimi 1: Krijon tabelën 'restaurants' nëse nuk ekziston
CREATE TABLE IF NOT EXISTS public.restaurants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migrimi 2: Shton kolonën 'rating' te porositë nëse nuk ekziston
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS rating TEXT CHECK (rating IN ('bad', 'ok', 'good'));

-- Migrimi 3: Vendos vlerën default për restaurant_id
-- Kjo siguron që çdo porosi, thirrje, ose artikull menuje i ri t'i përkasë automatikisht restorantit me ID 1
ALTER TABLE waiter_calls ALTER COLUMN restaurant_id SET DEFAULT 1;
ALTER TABLE orders ALTER COLUMN restaurant_id SET DEFAULT 1;
ALTER TABLE menu ALTER COLUMN restaurant_id SET DEFAULT 1;

-- Migrimi 4: Lidhim te gjitha te dhenat ekzistuese me restorantin 1
UPDATE menu SET restaurant_id = 1 WHERE restaurant_id IS NULL;
UPDATE orders SET restaurant_id = 1 WHERE restaurant_id IS NULL;
UPDATE waiter_calls SET restaurant_id = 1 WHERE restaurant_id IS NULL;