-- Table zones are a lightweight operational layer for waiter territories.
-- They intentionally do not replace order status colors; they only add a neutral label.

create table if not exists public.table_zones (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null default 1,
  label text not null,
  table_from integer not null,
  table_to integer not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint table_zones_valid_range check (table_from > 0 and table_to >= table_from),
  constraint table_zones_label_not_empty check (length(trim(label)) > 0)
);

create index if not exists idx_table_zones_restaurant_active
on public.table_zones (restaurant_id, active, table_from);

alter table public.table_zones enable row level security;

-- Service role is used by Edge Functions. Browser clients do not query this table directly.
drop policy if exists "Service role can manage table zones" on public.table_zones;
create policy "Service role can manage table zones"
on public.table_zones
for all
to service_role
using (true)
with check (true);

-- Default local setup. Adjust ranges per real restaurant.
insert into public.table_zones (restaurant_id, label, table_from, table_to, active)
values
  (1, 'Zona A', 1, 5, true),
  (1, 'Zona B', 6, 10, true),
  (1, 'Zona C', 11, 15, true)
on conflict do nothing;
